[package]
name = "rpmalloc-sys"
version = "0.3.0+2.0.1"
description = "Unsafe FFI bindings to rpmalloc C library"
authors = ["Embark <opensource@embark-studios.com>", "Johan Andersson <repi@repi.se>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/EmbarkStudios/rpmalloc-rs"
edition = "2018"
build = "build.rs"
keywords = ["allocator", "rpmalloc"]
categories = ["memory-management", "external-ffi-bindings"]
readme = "README.md"
workspace = ".."

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.14"
cc = "1"

[features]
default = []
statistics = []                 # Compile with ENABLE_STATISTICS=1
validate_args = []              # Compile with ENABLE_VALIDATE_ARGS=1
asserts = []                    # Compile with ENABLE_ASSERTS=1
leak_detection = ["statistics"] # Compile with ENABLE_LEAK_DETECTION=1
disable_unmap = []              # Compile with ENABLE_UNMAP=0
disable_decommit = []           # Compile with ENABLE_DECOMMIT=0
