on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # make sure all code has been formatted with rustfmt
      - run: rustup component add rustfmt
      - name: check rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --color always

      # run clippy to verify we have no warnings
      - run: rustup component add clippy
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --lib --tests -- -D warnings
      - name: cargo clippy (all features)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --lib --tests --all-features -- -D warnings

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # test default features
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
      # test all features
      # disabled for now because our tests leak which asserts catch on linux: https://github.com/EmbarkStudios/rpmalloc-rs/runs/284078500
      #- name: cargo test (all features)
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --all-features
